### ISSUE TITLE
PowerMock 2.0.3 not deployed to Maven Central

### ISSUE THREAD

**Issue by wezley98** [powermock/powermock#1015]
2.0.3 has not been deployed to Maven Central.

**Comment by floscher** [comment]
The GitHub release also wasn't created for 2.0.3: https://github.com/powermock/powermock/releases

Also: The link to BinTray on the GitHub release pages is broken, it points to [https://bintray.com/powermock/**null**/powermock/2.0.2](https://bintray.com/powermock/null/powermock/2.0.2)

**Comment by sfuhrm** [comment]
@thekingnothing would be great to see 2.0.4 here, maybe maven deploy was planned for a later time: 

https://mvnrepository.com/artifact/org.powermock/powermock-module-junit4

**Comment by thekingn0thing** [comment]
In general, Bintray should automatically sync repo to maven Center after a build publish artefact to bintray. I will check what went wrong with the sync today in the evening.

Cheers,
Artur

On 17 Oct 2019, at 08:26, Stephan Fuhrmann <notifications@github.com> wrote:

﻿

@thekingnothing<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthekingnothing&data=02%7C01%7C%7C860d87feb0994d9326a908d752d355df%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637068939934906839&sdata=8x3%2F3PPKmsru%2FBMAkBe0%2F%2FoefI5VJIUkj%2BE9ODWNwAo%3D&reserved=0> would be great to see 2.0.4 here, maybe maven deploy was planned for a later time:

https://mvnrepository.com/artifact/org.powermock/powermock-module-junit4<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmvnrepository.com%2Fartifact%2Forg.powermock%2Fpowermock-module-junit4&data=02%7C01%7C%7C860d87feb0994d9326a908d752d355df%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637068939934906839&sdata=GS90Cz3iOFTpgrI8y0r4NetENjAKgNgPucVL4%2Fd%2FRH0%3D&reserved=0>

**Comment by thekingn0thing** [comment]
Eveything went fine with release, please check maven central directly, not https://mvnrepository.com as this site indexes Maven center repository and leads to delays 
Last Synced:    Wed Oct 16 21:27:16 GMT 2019 
https://repo.maven.apache.org/maven2/org/powermock/powermock-module-junit4/2.0.4/
