### ISSUE TITLE
PowerMockito can't unbox Void

### ISSUE THREAD

**Issue by udayanpatel** [powermock/powermock#708]
PowerMockito doesn't seem to unbox java.lang.Void.
I am writing a test for my code that uses Google cloud storage API to delete a file. Google API returns Void for deleting a file. Code works fine but when I instruct my test as PowerMockito.doNothing().when(delete).execute(); It complains that execute has a return value of Void.

**Comment by thekingnothing** [comment]
It is not PowerMock issue. PowerMock just delegates call to Mockito in this case. I asked about expected  behaviour in Mockito's mailing list 
https://groups.google.com/forum/#!topic/mockito/uhRxkAdmonY

**Comment by thekingnothing** [comment]
Issue fixed by Mockito.
