### ISSUE TITLE
Spring boot with powermock using problem 

### ISSUE THREAD

**Issue by blueiceprj** [powermock/powermock#735]
`@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(SpringRunner.class)
@PrepareForTest({UI.class})
`

No spring boot application starting. Spring boot version 1.4.2 and powermockite version 1.6.6

Example code 

```
@RunWith(PowerMockRunner.class)
@PrepareForTest(UI.class)
@PowerMockRunnerDelegate(SpringRunner.class)
public class PowermockClassLoadTest {
    
    @Test
    public void testRest() throws Exception {
         PowerMockito.mockStatic(UI.class);
        .......
        final MrsUI mrsUi = mock(MrsUI.class);
        final UI ui = mock(UI.class);
       ........
        when(UI.getCurrent()).thenReturn(mrsUi);
       .....
    }

}

```

**Comment by zhanjiejun** [comment]
Have you solved the problem?

**Comment by blueiceprj** [comment]
Yes. Thank you very much.

**Comment by solimant** [comment]
@blueiceprj, would be nice to share how you solved the problem.

**Comment by blueiceprj** [comment]
I think, Powermock or spring or vaadin class loaders have conflict. I ignored some class loading from powermock then the problem solved. Like this,


`
@RunWith(PowerMockRunner.class) 
@PowerMockRunnerDelegate(SpringRunner.class) 
@PowerMockIgnore(value= {"javax.net.ssl.*","javax.net.SocketFactory","javax.security.auth.x500.X500Principal"})
`
