### ISSUE TITLE
Call to "whenNew()" and "withArguments(any(BlahBlah.class))" results in null value

### ISSUE THREAD

**Issue by davidmichaelkarr** [powermock/powermock#738]
I recently started the process of upgrading our unit tests from PowerMock 1.6.2 to 1.6.6, so I could integrate JaCoCo 0.7.8 (offline instrumentation).  I've managed to hit some sort of problem that seems to be related to the new feature in 1.6.6 to allow for checking constructor parameters in "whenNew()", although I had the impression that feature was about the "eq" operator.

Here is what a typical "whenNew()" block looks like:
`blahBlahInstance = new BlahBlah(someClassInstance);
PowerMockito.whenNew(BlahBlah.class)
				.withArguments(any(SomeClass.class))
				.thenReturn(blahBlahInstance);`

And in the code under test, it executes a block like this:
`return process(ctx, new BlahBlah(someClassInstance));`

In 1.6.2, this would properly returned the pre-created "blahBlahInstance".  In 1.6.6, it's returning NULL.  This causes many tests in our codebase to fail.

I've been trying to construct an isolated test case with similar structures that also repeats this problem, but I have not yet gotten it to fail.

If it matters, I posted about this issue at https://groups.google.com/forum/#!topic/powermock/vopByG0rKJk and http://stackoverflow.com/questions/41815826/after-upgrading-from-powermock-1-6-2-to-1-6-6-to-integrate-jacoco-0-7-8-a-when .

**Comment by thekingnothing** [comment]
When 'whenNew' doesn't work it two possible case:
* constructor with given set of parameters wasn't found. When you marchers PowerMock doesn't have direct access to parameter type. As I remember in this case PowerMock tries to find a constructor with same count of parameters. I don't have opportunity to check it right now. But anyway you can exclude this case by passing to 'whenNew' a constructor instead class
* Mockito proxy not match real call to register call. PowerMock creates a mock object via Mockito for constructor call and then delegate all constructor calls to this Mock object. This case you can check only in debug. 

If you cannot create a isolated test, I can guess that issue with with 'SomeClass'. Either constructor has parameter 'AnotherClass' and 'SomeClass' extents this class or it implements an interface. Also could be an issue with visibility, as I remember, you mentioned that you add 'SomeClass' to '@PrepareForTest'

**Comment by davidmichaelkarr** [comment]
One thing I left out of my code samples is a couple of lines just before it, which would look like this:
`blahBlahInstance = new BlahBlah(someClassInstance);` It has no trouble reaching and calling this constructor.

Concerning @PrepareForTest, I found that the workaround required both changes, adding "BlahBlah.class" to the @PrepareForTest list, and replacing "withArguments(any(...))" with "withAnyArguments()".

What do you mean by "you can exclude this case by passing to 'whenNew' a constructor instead class"?

**Comment by thekingnothing** [comment]
> What do you mean by "you can exclude this case by passing to 'whenNew' a constructor instead class"?

I meant that you may get constructor via `BlahBlah.class.getDeclaredConstructors()` and call `org.powermock.api.mockito.PowerMockito#whenNew(java.lang.reflect.Constructor<T>)`.

**Comment by thekingnothing** [comment]
@davidmichaelkarr, have you figured out how to reproduce issue? Have you tried passing constructor?

**Comment by davidmichaelkarr** [comment]
I have not figured out how to reproduce it in a standalone test case.

Just now I tried to change an existing failing test to instead use "getDeclaredConstructors", but I can't get it to compile.

The following method is what I'm working with:
`	public UnifiedExecuteCreditCheckResponseTO setupAndInvokeProcessor(
			SubmitUnifiedCreditApplicationRequestTO requestBean, String xmlPath) throws Exception {
		csiSubmitUnifiedCreditApplicationProcessor = new CsiSubmitUnifiedCreditApplicationProcessor(requestBean);
		csiSubmitUnifiedCreditApplicationProcessor.setSoapClient(soapClient);
		//PowerMockito.whenNew(CsiSubmitUnifiedCreditApplicationProcessor.class)
		PowerMockito.whenNew(CsiSubmitUnifiedCreditApplicationProcessor.class.getDeclaredConstructors()[0])
				//.withAnyArguments()
		.withArguments(any(SubmitUnifiedCreditApplicationRequestTO.class))
				.thenReturn(csiSubmitUnifiedCreditApplicationProcessor);
		stubReply(this.getClass(), xmlPath, soapClient);
		return service.resubmitCreditCheck(svcCtxt, request);
	}`

I commented out the "withAnyArguments()" call and replaced it with the original "withArguments(any(...))" call, and verified that the test now fails because it ends up returning null from the mocked constructor call.  So, I then commented out the "whenNew()" call to make it call "getDeclaredConstructors".  It only has a single constructor, so I just added "[0]" to the end of that.

However, Eclipse is claiming this doesn't compile. It puts a red mark on "thenReturn", and the "detailed" message says "The method thenReturn(capture#1-of ?) in the type OngoingStubbing<capture#1-of ?> is not applicable for the arguments (CsiSubmitUnifiedCreditApplicationProcessor)".  I don't know what to do with that.

**Comment by davidmichaelkarr** [comment]
I need to spend more time looking at this.  The test case that I spent time on today with this appears to be not a good test case for this, because this one in particular is testing what happens when the constructor parameter is NULL, so it wouldn't have matched the type matcher.  In this case, I guess that "withAnyArguments()" is actually the proper specification, and that makes the test pass.  I need to look again at the tests that I had to modify in the codebase, changing "withArguments()" to "withAnyArguments()", to see if there's really a verifiable problem here.  I find it hard to believe all of the cases I made this change were actually cases where the constructor parameter was null.

**Comment by davidmichaelkarr** [comment]
Sorry, but it looks like this whole thing was a bit of a red herring.  After further analysis, I determined that all of the failing cases using "withArguments(any(...))" were tests where it was verifying the behavior when the request object was null, so it wouldn't match that matcher.  I seem to remember some history of a conversation about this in Mockito. In these particular cases, I added a second "whenNew()" using "withAnyArguments()" to match the null value. I think we can close this.

**Comment by thekingnothing** [comment]
@davidmichaelkarr, thank you for investigation and providing detail information.

**Comment by sagartrehan** [comment]
@davidmichaelkarr I have a constructor which is taking few arguments. One of the argument is null. So as suggested by you I used withAnyArguments() property of withNew(..) but still PowerMock is not able to find the mock implementation and hence object is NULL.

Please suggest. 

Here is the code:

whenNew(FMController.class)
                .withAnyArguments()
                .thenReturn(fmController);

**Comment by davidmichaelkarr** [comment]
You'd have to show more details, and you should write a new posting with that, and not here, likely in StackOverflow.

**Comment by henri5** [comment]
I'm running into same issue when writing tests and I managed to create some minimal test case
```
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

@RunWith(PowerMockRunner.class)
@PrepareForTest({ Foo.class})
public class NullConstructorTest {

  @Test
  public void testBorkenArgumentMatchers() throws Exception {
    Bar url = PowerMockito.mock(Bar.class);
    PowerMockito.whenNew(Bar.class).withAnyArguments().thenReturn(url);
    new Foo();
  }
}
```
```
public class Foo {
  Foo() {
    Bar bar = new Bar(null);
    System.out.println(bar.toString());
  }
}
```
```
public class Bar {
  Bar(String s) {
  }
}
```
This test works with 1.6.5, but on 1.6.6 fails with NPE on `bar.toString()`.
