### ISSUE TITLE
1.7.0RC2 not available on bintray

### ISSUE THREAD

**Issue by justinmuller** [powermock/powermock#745]
I have not been able to fetch 1.7.0RC with gradle using the group/module listed on https://bintray.com/powermock/maven/powermock/powermock-1.7.0RC2 

1.7.0RC2 is not listed at https://repo.jfrog.org/artifactory/libs-release-bintray/org/powermock/powermock-api-mockito2/

Has 1.7.0RC2 been published?

**Comment by thekingnothing** [comment]
The PowerMock 1.7.0RC has only been published on to Bintray organisation: 
http://dl.bintray.com/powermock/maven/
I'm trying to resolve the issues that prevent publishing artifacts to Bintray jCenter. As soon as I resolve them release (I think it will be 1.7.0) will be published to Maven Central also.

**Comment by thekingnothing** [comment]
Now PowerMock 1.7.0RC2 available in Maven Central 
https://repo1.maven.org/maven2/org/powermock/powermock-api-mockito2/1.7.0RC2/
