### ISSUE TITLE
version 1.6.4 No ClassDef Found error PowerMockRule

### ISSUE THREAD

**Issue by coolprashi06** [powermock/powermock#752]
My test class has following annotations (project is based on spring boot web):

```
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = {Application.class})
@WebAppConfiguration
@PowerMockIgnore( { "org.springframework.*", "org.apache.log4j", "org.mockito.*" })
@PrepareForTest({MyStaticClass.class})
public class MyTest
```
My Test method has following code:

mockStatic(MyStaticClass.class);
when(MyStaticClass.getStaticMethod()).thenReturn(null);

but running mvn tests gives following error:
```
javax.xml.parsers.FactoryConfigurationError: Provider com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl could not be instantiated: java.lang.ClassCastException: com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl cannot be cast to javax.xml.parsers.SAXParserFactory

java.lang.NoClassDefFoundError: Could not initialize class org.powermock.modules.junit4.rule.PowerMockRule
```
using following dependencies in my pom.xml:
```
     <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>${powermock.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito</artifactId>
            <version>${powermock.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4-rule-agent</artifactId>
            <version>${powermock.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-classloading-xstream</artifactId>
            <version>${powermock.version}</version>
            <scope>test</scope>
        </dependency>
```

**Comment by thekingnothing** [comment]
Have you tried add `javax.xml` to `@PowerMockIgnore` ?

**Comment by coolprashi06** [comment]
will add that and let you know.
meanwhile just to let you know that MyStaticClass has private constructor too. would that create any issue?

**Comment by coolprashi06** [comment]
getting below error after adding javax.xml to PowerMockIgnore:

```
java.lang.LinkageError: loader constraint violation: when resolving overridden method "com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Lorg/xml/sax/InputSource;Lorg/xml/sax/helpers/DefaultHandler;)V" the class loader (instance of org/powermock/core/classloader/MockClassLoader) of the current class, com/sun/org/apache/xerces/internal/jaxp/SAXParserImpl, and its superclass loader (instance of <bootloader>), have different Class objects for the type org/xml/sax/helpers/DefaultHandler used in the signature
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl.newSAXParser(SAXParserFactoryImpl.java:79)
```

**Comment by thekingnothing** [comment]
Symptoms the same as in #743 and as it described in [blog](https://blog.jayway.com/2011/05/19/powermock-for-integration-testing/)

Now you need add `org.xml.*`. 

> meanwhile just to let you know that MyStaticClass has private constructor too. would that create any issue?

Nope, PowerMock uses [objenesis](http://objenesis.org) library to create an instance of object if it required.

**Comment by coolprashi06** [comment]
my problem is powermock is not working properly with SpringJUnit4ClassRunner 

my project is based on spring boot and spring mvc. there is a BaseTest class with following annotations:

```
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = {Application.class, MongoConfiguration.class})
@WebAppConfiguration
```

and all the test classes extending from this base class. now using annotations @PrepareForTest({MyStaticClass.class}) and @Rule PowerMockRule too doesn;t work.

I also commented on https://github.com/powermock/powermock/issues/597 but did not get reply. I believe this is alternative to PowerMockRunner.

**Comment by thekingnothing** [comment]
Have you tried to use '@PowerMockDelegate' ?

As I remember #597 is about that class located in another library than it expected. To fix it, adding agent library on one of classloading is enough.

Third way - use Powermock agent

https://github.com/powermock/powermock/wiki/PowerMockAgent

But exceptions show that you have issue with class loaders. Some classes are loaded by Powermock class loader, some not.

Best regrads,
Arthur Zagretdinov


On 9 Feb 2017, at 19:50, Prashast Saxena <notifications@github.com<mailto:notifications@github.com>> wrote:


my problem is powermock is not working properly with SpringJUnit4ClassRunner

my project is based on spring boot and spring mvc. there is a BaseTest class with following annotations:

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = {Application.class, MongoConfiguration.class})
@WebAppConfiguration


and all the test classes extending from this base class. now using annotations @PrepareForTest({MyStaticClass.class}) and @Rule<https://github.com/Rule> PowerMockRule too doesn;t work.

I also commented on #597<https://github.com/powermock/powermock/issues/597> but did not get reply. I believe this is alternative to PowerMockRunner.

**Comment by coolprashi06** [comment]
When i use PowerMockRule and initialize PowerMockAgent too that don't work too.

In that wiki I don't understand the below:
It's recommended that you put powermock-module-junit4-rule-agent before junit in the classpath.

**Comment by CyborgMaster** [comment]
I have the same problem.  It shows up only when I upgrade `mockito-core` to  2.0.4-beta, it doesn't have this problem on 2.0.3-beta.

**Comment by msangel** [comment]
Don't want to use any additional agents, as in my project there are a bunch of them and they are not fit well together. 
Using powermock-classloading-xstream fix the problem but still preferred fix with original loader. 
ver. 1.7.4
