### ISSUE TITLE
[Documentation] File links pointing to google still

### ISSUE THREAD

**Issue by TehBakker** [powermock/powermock#754]
Hey there,

Not sure if this is the place for it, but you a head up that the link in the References here : https://github.com/powermock/powermock/wiki/MockStatic#references are still pointing to http://code.google.com/p/powermock/source/browse/trunk/examples/DocumentationExamples/src/test/java/powermock/examples/staticmocking/ServiceRegistratorTest.java which redirect to github.

Regards

**Comment by thekingnothing** [comment]
Thank you! I fixed links.
