### ISSUE TITLE
Can someone publish the old versions of powermock to central?

### ISSUE THREAD

**Issue by zymzxq** [powermock/powermock#757]
My company is still using some old version of powermock, e.g. 1.3.8, 1.2.5, 1.3.1. We used to get them from googlecode's maven repo. But now the repo is gone. We can try to upgrade to newer version. But considering the number of projects that depends on them, it will be a lot of work. It would be nice if someone can release them to maven central or jcenter.

Cheers,
Chandler

**Comment by thekingnothing** [comment]
In theory, may be it possible to build and publish old version, but not in practice.  It could take a lot of time make such old releases.

**Comment by ColinHebert** [comment]
@thekingnothing, would it be possible to just upload the binaries for these artifacts? To at least provide non broken dependencies?

**Comment by thekingnothing** [comment]
@ColinHebert to which service are you want to upload the binaries?

**Comment by ColinHebert** [comment]
Central would be fantastic, if not, bintray?

**Comment by zymzxq** [comment]
Yeah, we have the list of files (jar, pom, source jar). But not every artifact has a complete list, e.g., some only has a jar file
