### ISSUE TITLE
org.powermock.reflect.exceptions.FieldNotFoundException: No instance field named XXX could be found in the class hierarchy

### ISSUE THREAD

**Issue by hazems** [powermock/powermock#773]
After upgrading to powerMock Version 1.7.0RC2 in order to work with mockito 2.1, some of the old tests which were using org.powermock.reflect.Whitebox's getInternalState() API failed because the API fails to find a private final String in the object.

Sample code
```
@RunWith(PowerMockRunner.class)
public class SampleTest {
    private MainObject testSubject;
    private String myPreferences;

    @Before
    public void setUp() {
        myPreferences = Whitebox.getInternalState(testSubject, "myPreferences").toString();
    }
	
    // test methods here ...
 }
```

**Comment by thekingnothing** [comment]
@hazems, 

As I understand  `MainObject` has structure like this: 

```

public class MainObject {
// some fields ... 

private final String myPreferences = "bla bla";
 
// some fields ... and methods ... 
}

```

Am I right?

**Comment by hazems** [comment]
@thekingnothing I figured out how to make it work, when I just used Whitebox.getInternalState(MainObject.class, "myPreferences") since it was a static final variable.

Thanks a lot for your support, I'm closing this issue now.
