### ISSUE TITLE
Real equals static methods are called instead of mocked

### ISSUE THREAD

**Issue by Ilya-Gh** [powermock/powermock#781]
Real equals static methods are called instead of mocked for equals static methods that are called from a stub. 

```
public class SpyObject {
    public boolean callEquals() {
        return EqualsStatic.equals();
    }
}
```

```
public class EqualsStatic {

    public static boolean equals() {
        return false;
    }
}
```

```
@RunWith(PowerMockRunner.class)
@PrepareForTest(EqualsStatic.class)
public class SpyTest {

    private SpyObject partialMock = null;

    @Before
    public void setup() throws Exception {
        PowerMockito.mockStatic(EqualsStatic.class);
        PowerMockito.when(EqualsStatic.equals()).thenReturn(true);

        partialMock = spy(new SpyObject());
    }

    @Test
    public void testCallEquals() {
        //fail
        assertTrue(partialMock.callEquals());
    }
}


```

It occurs because in MockGateway#doMethodCall methods MockGateway#tryHandleEqualsMethod
is invoked where following statement seems triggers reals method invocation:

```
if (calledFromMockito()){
    return PROCEED;
}


```

**Comment by ajitqait** [comment]
PowerMockito.mockStatic(Objects.class);
PowerMockito.when(Objects.nonNull(Mockito.anyObject())).thenReturn(true);

its calling real Objects.nonNull() method and returning false

is anyone faced this issue and if solved so please let me know

i m using mockito version: 

    testCompile("org.mockito:mockito-core:2.0.5-beta")
    testCompile('org.powermock:powermock-api-mockito:1.6.2')
    testCompile('org.powermock:powermock-module-junit4:1.6.2')
