### ISSUE TITLE
reset/unmock a class after I do PowerMockito.mockStatic(MY_CLASS.class)

### ISSUE THREAD

**Issue by LeftLegAndRightLeg** [powermock/powermock#785]
Hi Guys,

I cannot find a way to reset/unmock a class after I do PowerMockito.mockStatic(MY_CLASS.class)

is there gonna be a way to do it ?

Best,
Bailiang

**Comment by thekingnothing** [comment]
Hi, 

As workaround you may use `PrepareForTest()` on method level, in this case a new class will loaded for each test case and mock state will be reset. 

Unfortunately, where is no way to  reset/unmock after you once mocked it within test method.  I create a new issue for this feature (#787)
