### ISSUE TITLE
Docs unclear: Last version of PowerMock to work with Mockito 1.x?

### ISSUE THREAD

**Issue by christianbalzer** [powermock/powermock#789]
The docs are a bit unclear as to what the last version of PowerMock is that supports Mockito 1.x
https://github.com/powermock/powermock/wiki/MockitoUsage#supported-versions

Is it 1.6.2, 1.6.4, 1.6.5, 1.7.0RC2?

**Comment by thekingnothing** [comment]
Wiki is updated
