### ISSUE TITLE
java.lang.VerifyError: Inconsistent stackmap frames at branch target 1266

### ISSUE THREAD

**Issue by xtdw12345** [powermock/powermock#790]
java.lang.VerifyError: Inconsistent stackmap frames at branch target 1266
Exception Details:
  Location:
    com/rkhd/sns/dal/dao/impl/DBAgentHibernateImpl.getOrderedCrossList(Ljava/lang/Object;Ljava/lang/String;Lcom/rkhd/sns/dal/dao/model/SqlInfo;Ljava/lang/Long;Ljava/lang/Long;IZ)Ljava/util/List; @1256: if_acmpeq
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @1256
    flags: { }
    locals: { 'com/rkhd/sns/dal/dao/impl/DBAgentHibernateImpl', 'java/lang/Object', 'java/lang/String', 'com/rkhd/sns/dal/dao/model/SqlInfo', 'java/lang/Long', 'java/lang/Long', integer, integer, integer, 'java/util/List', top, 'java/lang/Long', long, long_2nd, null }
    stack: { long, long_2nd, 'java/lang/Long', null }
  Stackmap Frame:
    bci: @1266
    flags: { }
    locals: { 'com/rkhd/sns/dal/dao/impl/DBAgentHibernateImpl', 'java/lang/Object', 'java/lang/String', 'com/rkhd/sns/dal/dao/model/SqlInfo', 'java/lang/Long', 'java/lang/Long', integer, integer, integer, 'java/util/List', top, 'java/lang/Long' }
    stack: { top, long, long_2nd }
  Bytecode:
    0000000: 2a13 03d7 1007 bd01 0659 032b 5359 042c
    0000010: 5359 052d 5359 0619 0453 5907 1905 5359
    0000020: 0800 0000 0015 0636 0c01 3a0b 013a 0d13
    0000030: 1167 b811 6904 bd01 0659 03bb 0079 5915
    0000040: 0cb7 116b 5313 116c b811 6eb8 1170 3a0e
    0000050: 190e b211 72a5 0034 190e c104 6099 0022
    0000060: b811 7413 1175 b811 7713 0106 01b6 1179
    0000070: b611 7b01 b611 7dc0 0079 3a0d a700 0a19
    0000080: 0ec0 0079 3a0d a700 0ebb 0079 5915 0cb7
    0000090: 117f 3a0d 190d 5359 1006 0000 0000 1507
    00000a0: 360c 013a 0b01 3a0d 1311 80b8 1182 04bd
    00000b0: 0106 5903 bb03 7059 150c b711 8453 1311
    00000c0: 85b8 1187 b811 893a 0e19 0eb2 118b a500
    00000d0: 3419 0ec1 0460 9900 22b8 118d 1311 8eb8
    00000e0: 1190 1301 0601 b611 92b6 1194 01b6 1196
    00000f0: c003 703a 0da7 000a 190e c003 703a 0da7
    0000100: 000e bb03 7059 150c b711 983a 0d19 0d53
    0000110: 1303 ddb8 03df 1303 e0b8 03e2 3a08 1908
    0000120: 013a 0b01 3a0c 190b 1311 99b8 119b 1311
    0000130: 9c13 119d b811 9fb8 11a1 3a0d 190d b211
    0000140: a3a6 000b b203 e43a 0ca7 000a 190d c003
    0000150: ab3a 0c19 0ca5 0009 1908 c003 beb0 1904
    0000160: 3a0b 0336 0c01 3a0d 190b 01a5 000a 190b
    0000170: 3a0d a700 0b13 11a4 b811 a63a 0d19 0d13
    0000180: 11a7 03bd 0106 1311 a8b8 11aa 1311 acb8
    0000190: 11ae 3a0e 190e b211 b0a6 000d 190b b611
    00001a0: b236 0ca7 000d 190e c004 f5b6 11b4 360c
    00001b0: 150c 3608 1508 9c00 0603 3608 0000 0000
    00001c0: 013a 0b01 3a0c 1311 b5b8 11b7 03bd 0106
    00001d0: 1311 b8b8 11ba b811 bc3a 0d19 0db2 11be
    00001e0: a500 3419 0dc1 0460 9900 22b8 11c0 1311
    00001f0: c1b8 11c3 1301 0601 b611 c5b6 11c7 01b6
    0000200: 11c9 c000 633a 0ca7 000a 190d c000 633a
    0000210: 0ca7 000c bb00 6359 b711 cb3a 0c19 0c3a
    0000220: 092a 2b2c 2d03 360c 013a 0b01 3a0d 013a
    0000230: 0e19 0b01 a500 0a19 0b3a 0ea7 000b 1311
    0000240: cdb8 11cf 3a0e 190e 1311 d004 bd01 0659
    0000250: 03bb 0079 5915 0cb7 11d2 5313 11d3 b811
    0000260: d513 11d6 b811 d83a 0f19 0fb2 11da a600
    0000270: 0d15 0cb8 11dc 3a0d a700 0a19 0fc0 11dd
    0000280: 3a0d 190d 0000 0000 0000 0000 013a 0b01
    0000290: 3a0c 1311 deb8 11e0 03bd 0106 1311 e1b8
    00002a0: 11e3 b811 e53a 0d19 0db2 11e7 a500 3419
    00002b0: 0dc1 0460 9900 22b8 11e9 1311 eab8 11ec
    00002c0: 1301 0601 b611 eeb6 11f0 01b6 11f2 c001
    00002d0: 693a 0ca7 000a 190d c001 693a 0ca7 000c
    00002e0: bb00 1859 b711 f43a 0c19 0c12 733a 0c3a
    00002f0: 0b01 3a0d 013a 0e19 0b01 a500 0a19 0b3a
    0000300: 0ea7 000b 1311 f5b8 11f7 3a0e 190e 1311
    0000310: f804 bd01 0659 0319 0c53 1311 f9b8 11fb
    0000320: 1311 fcb8 11fe 3a0f 190f b212 00a6 000f
    0000330: 190b 190c b612 023a 0da7 000a 190f c005
    0000340: 653a 0d19 0d15 0836 0c3a 0b01 3a0d 013a
    0000350: 0e19 0b01 a500 0a19 0b3a 0ea7 000b 1312
    0000360: 03b8 1205 3a0e 190e 1312 0604 bd01 0659
    0000370: 03bb 0079 5915 0cb7 1208 5313 1209 b812
    0000380: 0b13 120c b812 0e3a 0f19 0fb2 1210 a600
    0000390: 0f19 0b15 0cb6 1212 3a0d a700 0a19 0fc0
    00003a0: 0565 3a0d 190d 1905 3a0c 3a0b 013a 0d01
    00003b0: 3a0e 190b 01a5 000a 190b 3a0e a700 0b13
    00003c0: 1213 b812 153a 0e19 0e13 1216 04bd 0106
    00003d0: 5903 190c 5313 1217 b812 1913 121a b812
    00003e0: 1c3a 0f19 0fb2 121e a600 0f19 0b19 0cb6
    00003f0: 1220 3a0d a700 0a19 0fc0 0565 3a0d 190d
    0000400: 3a0b 013a 0c01 3a0d 190b 01a5 000a 190b
    0000410: 3a0d a700 0b13 1221 b812 233a 0d19 0d13
    0000420: 1224 03bd 0106 1312 25b8 1227 1312 28b8
    0000430: 122a 3a0e 190e b212 2ca6 000d 190b b612
    0000440: 2e3a 0ca7 000a 190e c005 553a 0c19 0c3a
    0000450: 0c01 3a0b 013a 0d13 122f b812 3104 bd01
    0000460: 0659 0319 0c53 1312 33b8 1235 b812 373a
    0000470: 0e19 0eb2 1239 a500 3419 0ec1 0460 9900
    0000480: 22b8 123b 1312 3cb8 123e 1301 0601 b612
    0000490: 40b6 1242 01b6 1244 c000 793a 0da7 000a
    00004a0: 190e c000 793a 0da7 000e bb00 7959 190c
    00004b0: b712 463a 0d19 0d15 06b6 007b 3a0a 190a
    00004c0: 1507 b800 7c3a 0915 0819 09b9 0040 0100
    00004d0: 0464 a400 0619 09b0 1508 8519 053a 0b09
    00004e0: 370c 013a 0e19 0b01 a500 0a19 0b3a 0ea7
    00004f0: 000b 1312 47b8 1249 3a0e 190e 1312 4a03
    0000500: bd01 0613 124b b812 4d13 124e b812 503a
    0000510: 0f19 0fb2 1252 a600 0d19 0bb6 1254 370c
    0000520: a700 0d19 0fc0 04f5 b612 5637 0c16 0c61
    0000530: 1909 b900 4001 0085 949e 0014 1909 1508
    0000540: 1909 b900 4001 00b9 007e 0300 b019 0915
    0000550: 0815 0819 053a 0b03 360c 013a 0d19 0b01
    0000560: a500 0a19 0b3a 0da7 000b 1312 57b8 1259
    0000570: 3a0d 190d 1312 5a03 bd01 0613 125b b812
    0000580: 5d13 125e b812 603a 0e19 0eb2 1262 a600
    0000590: 0d19 0bb6 1264 360c a700 0d19 0ec0 04f5
    00005a0: b612 6636 0c15 0c60 b900 7e03 00b0     
  Stackmap Table:
    full_frame(@127,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Top,Top,Object[#262]},{Object[#261],Object[#260],Object[#1029],Object[#1029],Integer})
    full_frame(@134,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Top,Object[#121]},{Object[#261],Object[#260],Object[#1029],Object[#1029],Integer})
    full_frame(@137,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Integer},{Object[#261],Object[#260],Object[#1029],Object[#1029],Integer})
    full_frame(@148,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Top,Object[#121]},{Object[#261],Object[#260],Object[#1029],Object[#1029],Integer})
    full_frame(@248,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Top,Top,Object[#262]},{Object[#261],Object[#260],Object[#1029],Object[#1029],Integer})
    full_frame(@255,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Top,Object[#880]},{Object[#261],Object[#260],Object[#1029],Object[#1029],Integer})
    full_frame(@258,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Integer},{Object[#261],Object[#260],Object[#1029],Object[#1029],Integer})
    full_frame(@269,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Top,Object[#880]},{Object[#261],Object[#260],Object[#1029],Object[#1029],Integer})
    full_frame(@332,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Object[#262],Top,Top,Top,Top,Object[#262]},{Object[#262]})
    full_frame(@339,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Object[#262],Top,Top,Top,Object[#262]},{Object[#262]})
    full_frame(@350,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer},{})
    full_frame(@373,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Object[#304]},{})
    append_frame(@381,Top,Object[#262])
    full_frame(@422,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Top,Top,Object[#262]},{})
    full_frame(@432,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Integer},{})
    full_frame(@444,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer},{})
    full_frame(@522,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Object[#262]},{})
    full_frame(@529,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Object[#99]},{})
    full_frame(@532,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer},{})
    full_frame(@541,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Object[#99]},{})
    full_frame(@574,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Integer},{Object[#261],Object[#262],Object[#260],Object[#512]})
    full_frame(@582,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Integer,Top,Object[#431]},{Object[#261],Object[#262],Object[#260],Object[#512]})
    full_frame(@635,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Top,Top,Object[#262]},{Object[#261],Object[#262],Object[#260],Object[#512]})
    full_frame(@642,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Object[#121]},{Object[#261],Object[#262],Object[#260],Object[#512]})
    full_frame(@726,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Object[#262]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@733,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Object[#361]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@736,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@745,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Object[#361]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@772,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Object[#361],Object[#260]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@780,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Object[#361],Object[#260],Top,Object[#262]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@828,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Top,Top,Object[#262]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@835,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Object[#361]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@862,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Object[#361],Integer},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@870,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Object[#361],Integer,Top,Object[#262]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@925,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Top,Top,Object[#262]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@932,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Object[#361]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@959,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Object[#361],Object[#304]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@967,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Object[#361],Object[#304],Top,Object[#262]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@1015,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Top,Top,Object[#262]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@1022,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Object[#361]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@1045,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Object[#361]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@1053,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Object[#361],Top,Object[#262]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@1094,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Top,Object[#262]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@1101,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Object[#260]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@1184,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Top,Object[#262]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@1191,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Object[#121]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@1194,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Object[#260]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@1205,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Top,Top,Top,Top,Object[#121]},{Object[#261],Object[#262],Object[#260],Object[#512],Object[#121]})
    full_frame(@1240,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Object[#317]},{})
    full_frame(@1266,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Object[#317],Top,Object[#304]},{Top,Long})
    full_frame(@1274,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Object[#317],Top,Object[#304],Top,Top,Object[#262]},{Top,Long})
    full_frame(@1315,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Object[#317],Top,Top,Top,Top,Top,Object[#262]},{Top,Long})
    full_frame(@1325,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Integer,Object[#317],Top,Top,Long},{Top,Long})
    chop_frame(@1357,3)
    full_frame(@1386,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Object[#304]},{Object[#317],Integer,Integer})
    full_frame(@1394,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Object[#304],Top,Object[#262]},{Object[#317],Integer,Integer})
    full_frame(@1435,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Top,Top,Object[#262]},{Object[#317],Integer,Integer})
    full_frame(@1445,{Object[#261],Object[#262],Object[#260],Object[#512],Object[#304],Object[#304],Integer,Integer,Top,Top,Top,Top,Integer},{Object[#317],Integer,Integer})

	at com.rkhd.sns.dal.dao.impl.DBAgentHibernateImplTest.save_normalObject_returnObjectId(DBAgentHibernateImplTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:66)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:312)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:94)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:296)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:112)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:73)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:284)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:84)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:209)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:148)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:102)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:42)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)

**Comment by yujishe** [comment]
hi! I also ran into the same problem, but I found that the jar error resulted in the addition of the mockito-all.XX.jar in my project, which resulted in the collision of the jar bundle.I solved this problem and powermock was running success.I hope my experience will help you.

**Comment by thekingnothing** [comment]
@yujishe, thank you for information. Yeah, it could be an issue with classpath. PowerMock uses Javassist for byte code modification and if  you exception like this `java.lang.VerifyError` in most cases it means that you have old version of Javassist in class path and better to with latest version of the library .

**Comment by 733** [comment]
Staph it

Wysłane z iPhone'a

Dnia 26.05.2017 o godz. 08:05 Arthur Zagretdinov <notifications@github.com> napisał(a):
