### ISSUE TITLE
links on "GettingStarted" deprecated

### ISSUE THREAD

**Issue by noelo-cohelo** [powermock/powermock#792]
On **Mockito2 JUnit Maven Setup** I think it should be https://github.com/powermock/powermock/wiki/Mockito-2-(Maven), also:
**Mocking static methods**
**Expect new instance**
**Suppress constructor**
**Mocking private methods with JUnit 3**
point to 404.

**Comment by thekingnothing** [comment]
Thank you for reporting. I fixed links.
