### ISSUE TITLE
PowerMockMaker for Mockito 2

### ISSUE THREAD

**Issue by thekingnothing** [powermock/powermock#793]
PowerMockMaker should delegate creating mock object to default Mockito MockMaker if test does not use PowerMock feature like `@PrepareForTest`, `@SupressStaticInitilization` and so on. 

PowerMock breaks a new feature of Mockito 2, because it mocking final classes and methods without PowerMock.

**Comment by thekingnothing** [comment]
Fixed by adding `mockito.mock-maker-class=mock-maker-inline` to PowerMock configuration properties file.

**Comment by thekingnothing** [comment]
More information how to use a new feature will be added later to wiki.

**Comment by manuelvicnt** [comment]
Thanks for the fix. When are you thinking of releasing this new version? I think a lot of people need this asap. Thank you @thekingnothing

**Comment by thekingnothing** [comment]
Hi,

I was going to drop release at the end of this week, but due to some points that was raised in discussion with Mockito team (https://github.com/mockito/mockito/issues/1110), I'm thinking about postponing the release.

Best regrads,
Arthur Zagretdinov

On 12 Jun 2017, at 17:55, Manuel Vivo <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the fix. When are you thinking of releasing this new version? I think a lot of people need this asap. Thank you @thekingnothing<https://github.com/thekingnothing>
