### ISSUE TITLE
Use Mockito Shipkit for CD

### ISSUE THREAD

**Issue by thekingn0thing** [powermock/powermock#826]
Change build configuration and use https://github.com/mockito/shipkit tool to be able to release PowerMock after each pull request.

**Comment by thekingn0thing** [comment]
Previously, main issue was: PowerMock creates additional artifacts like zip files and full jars that have to be uploaded to separate Bintray repository without syncing with Maven central.

**Comment by thekingn0thing** [comment]
First implementation #829

**Comment by thekingn0thing** [comment]
@wwilk, thank you for your help. I have merged your pull request. 
I have the following questions: 

- Will the zip files be built and uploaded during release? 
- Where should be  bintray configuration? in shipkit.gradle?
- Can I delete version.gradle?  
- Could you help me to generate for each release not only release-notes, but [download page](https://github.com/powermock/powermock/wiki/Downloads) also?

**Comment by thekingn0thing** [comment]
@wwilk, could explain how does `[ci maven-central-release]` work? I think that PowerMock also is needed in it.

**Comment by thekingn0thing** [comment]
@wwilk, one more question: is it possible to customise tag name?

**Comment by wwilk** [comment]
@thekingnothing Starting from the end, at the moment only thing about tag that you can customize is its prefix. See https://github.com/mockito/shipkit/blob/d04e237c8d32fdc83f59d8ea2b105cc02620abff/src/main/groovy/org/shipkit/gradle/configuration/ShipkitConfiguration.java#L37

**Comment by wwilk** [comment]
> Will the zip files be built and uploaded during release?

I don't see them uploaded in Bintray test release that I made, I will check it out tomorrow. 

> Where should be bintray configuration? in shipkit.gradle?

Yes, it's the best place, I only tried it on shipkit-boostrap repo, obviously the production configuration can be only tested by you, but you can basically copy paste most of it, because we use the same BintrayExtension for configuration.

> Can I delete version.gradle?

You mean version.properties? We only support version storage in this file at the moment, if it's a problem for you, we can create an issue for it. Where would you prefer to store it?

> Could you help me to generate for each release not only release-notes, but download page also?

AFAIK we don't have this feature yet, so it would be best to create an issue for it.

**Comment by thekingn0thing** [comment]
@wwilk do you have an issue for it? If not I'll create.

Best regrads,
Arthur Zagretdinov

On 6 Aug 2017, at 21:35, Wojtek Wilk <notifications@github.com<mailto:notifications@github.com>> wrote:


@thekingnothing<https://github.com/thekingnothing> Starting from the end, at the moment only thing about tag that you can customize is its prefix. See https://github.com/mockito/shipkit/blob/d04e237c8d32fdc83f59d8ea2b105cc02620abff/src/main/groovy/org/shipkit/gradle/configuration/ShipkitConfiguration.java#L37

**Comment by thekingn0thing** [comment]
@wwik,
> I don't see them uploaded in Bintray test release that I made, I will check it out tomorrow.

They are uploaded by separate bintray task, because they should locate in separate repository and not synced with Maven. So I think it should be additional configuration and task that will be called during release after checking that release is required but before changing version and pushing to Git.

> You mean version.properties?

No, I meant exactly `version.gradle` that was copy-past from Mockito and that creates a version object.

Best regrads,
Arthur Zagretdinov

On 6 Aug 2017, at 21:44, Wojtek Wilk <notifications@github.com<mailto:notifications@github.com>> wrote:


Will the zip files be built and uploaded during release?
I don't see them uploaded in Bintray test release that I made, I will check it out tomorrow.

Where should be bintray configuration? in shipkit.gradle?
Yes, it's the best place, I only tried it on shipkit-boostrap repo, obviously the production configuration can be only tested by you, but you can basically copy paste most of it, because we use the same BintrayExtension for configuration.

Can I delete version.gradle?
You mean version.properties? We only support version storage in this file at the moment, if it's a problem for you, we can create an issue for it. Where would you prefer to store it?

Could you help me to generate for each release not only release-notes, but download page also?
AFAIK we don't have this feature yet, so it would be best to create an issue for it.

**Comment by wwilk** [comment]
No, no issue for customizing tag name yet, please create it. 

> They are uploaded by separate bintray task, because they should locate in separate repository and not synced with Maven. So I think it should be additional configuration and task that will be called during release after checking that release is required but before changing version and pushing to Git.

OK, I will see tomorrow if it would be possible to easily include it in the performRelease.

> No, I meant exactly `version.gradle` that was copy-past from Mockito and that creates a version object.

Would you please send me a link to this file in mockito repo? I can't find it.

**Comment by thekingn0thing** [comment]
In Mockito repository the `version.gradle` was deleted. Here you may find old version: https://github.com/mockito/mockito/blob/74ddc9933cf922c4153da21fae6c9afa083944ce/gradle/version.gradle



Best regrads,
Arthur Zagretdinov

On 6 Aug 2017, at 23:01, Wojtek Wilk <notifications@github.com<mailto:notifications@github.com>> wrote:


No, no issue for customizing tag name yet, please create it.

They are uploaded by separate bintray task, because they should locate in separate repository and not synced with Maven. So I think it should be additional configuration and task that will be called during release after checking that release is required but before changing version and pushing to Git.

OK, I will see tomorrow if it would be possible to easily include it in the performRelease.

No, I meant exactly version.gradle that was copy-past from Mockito and that creates a version object.

Would you please send me a link to this file in mockito repo? I can't find it.

**Comment by wwilk** [comment]
Thanks, this file is not needed any more.

**Comment by thekingn0thing** [comment]
Blockers: 

- [x] PowerMock CR: customisable tag name https://github.com/mockito/shipkit/issues/333
- [x] PowerMock CR: call additional task before bumping version. https://github.com/mockito/shipkit/issues/334

**Comment by mockitoguy** [comment]
>could explain how does [ci maven-central-release] work? I think that PowerMock also is needed in it.

Is it needed? "[ci maven-central-release]" is Mockito-specific. Can we ship every pull request to Powermock to Maven Central as Shipkit default behavior? It is simple and culture-shifting for continuous delivery!

**Comment by thekingn0thing** [comment]
Yep, it's needed. I do not want to put all release to Maven Central. There are several reasons: 
- Regression is normal for PowerMock. It does not have so good tests safe-net. 
- I'm going to drop several release candidate of PowerMock 2, before final due to first point.

**Comment by thekingn0thing** [comment]
@wwilk, thank you for help! I've merged change to release branch and everything works fine. I haven't checked publishing to maven central because there is no change in code. I'll check it when a bug fix or improvement will be provided.
