### ISSUE TITLE
java.lang.IllegalStateException: no last call on a mock available

### ISSUE THREAD

**Issue by DivyashreeMS** [powermock/powermock#847]
Hey there and thank you for using PowerMock

Please read the following tips before filing an issue:

Is this something you can debug and fix?

Tried all possible ways to resolve the issue but no luck.
I am pasting the code. Requesting team to review and resolve the issue for which I am facing

Code:

package com.mastercard.edcp.securityframework.manager;

import static org.easymock.EasyMock.expect;
import static org.powermock.api.easymock.PowerMock.mockStatic;
import java.io.File;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import com.mastercard.edcp.securityframework.common.EnvConfigs;

@RunWith(PowerMockRunner.class)
@PrepareForTest(UpdateCapIdManager.class)
public class UpdateCapIdManagerTest {

	private UpdateCapIdManager updateCapIdManager;

	@Before
	public void setUp() {
		updateCapIdManager = new UpdateCapIdManager();
	}

	@Test
	public void testUpdateCapIdInCDM() {

		String file = "file/modifyCapID.txt";
		String actualFilePath = getFile(file);
		mockStatic(EnvConfigs.class);
		expect(EnvConfigs.getCapIdUpdteFilePath()).andReturn(actualFilePath);

		updateCapIdManager.init();

		updateCapIdManager.updateCapIdInCDM();
	}

	private String getFile(String fileName) {

		// Get file from resources folder
		ClassLoader classLoader = getClass().getClassLoader();
		File file = new File(classLoader.getResource(fileName).getFile());
		return file.getAbsolutePath();

	}

}

public class UpdateCapIdManager {
public void init() {		
		cmdCapIdUpdteFilePath = EnvConfigs.getCapIdUpdteFilePath();
		
		logger.debug("cmdCapIdUpdteFilePath = " + cmdCapIdUpdteFilePath);		
	}
}
-------------------------------------------------------

Can you see anything in the logs? Can you debug why this happens? **Send a pull request**! Bug fixes and documentation fixes are very welcome.

Is this question about PowerMock usage?
---------------------------------------

The better way to ask question:

* The PowerMock [mailing-list](https://groups.google.com/forum/#!forum/powermock/)
* [Stackoverflow](http://stackoverflow.com/questions/tagged/powermock) with the tag 'powermock'. (Make sure you **include a short code snippet to demonstrate the problem** and if you have an exception then make sure **include stack trace**.)

None of the above, want to create a GitHub issue
------------------------------------------------------------------

Issues should always have a [Short, Self Contained, Correct (Compilable)](http://sscce.org), Example (same as any question on stackoverflow.com)

In order to help us to clarify issue can you answer the following question:

What steps will reproduce the problem?
What is the expected output?
What do you see instead?
What version of the product are you using?

**Comment by wodencafe** [comment]
You're not using `PowerMock.replay(EnvConfigs.class)`
