### ISSUE TITLE
2.0.0-beta.5 no dependency information available

### ISSUE THREAD

**Issue by freddyboucher** [powermock/powermock#854]
I'm just testing **powermock-2.0.0-beta.5**

But cannot compile my project because **no dependency information available**

> Downloading: https://repo.maven.apache.org/maven2/org/powermock/powermock-module-junit4/powermock-2.0.0-beta.5/powermock-module-junit4-powermock-2.0.0-beta.5.pom
[WARNING] The POM for org.powermock:powermock-module-junit4:jar:powermock-2.0.0-beta.5 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/powermock/powermock-api-mockito2/powermock-2.0.0-beta.5/powermock-api-mockito2-powermock-2.0.0-beta.5.pom
[WARNING] The POM for org.powermock:powermock-api-mockito2:jar:powermock-2.0.0-beta.5 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/powermock/powermock-module-junit4/powermock-2.0.0-beta.5/powermock-module-junit4-powermock-2.0.0-beta.5.jar
Downloading: https://repo.maven.apache.org/maven2/org/powermock/powermock-api-mockito2/powermock-2.0.0-beta.5/powermock-api-mockito2-powermock-2.0.0-beta.5.jar

> [ERROR] Failed to execute goal on project learnkeeper-server: Could not resolve dependencies for project com.learnkeeper:learnkeeper-server:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.powermock:powermock-module-junit4:jar:powermock-2.0.0-beta.5, org.powermock:powermock-api-mockito2:jar:powermock-2.0.0-beta.5: Could not find artifact org.powermock:powermock-module-junit4:jar:powermock-2.0.0-beta.5 in 3rd-party-repository (file:///Users/freddyboucher/Private/Programming/LearnKeeper/learnkeeper-server/../3rd-party-repository) -> [Help 1]

**Comment by thekingn0thing** [comment]
It seams that you specified incorrect version: "powermock-2.0.0-beta.5" instead "2.0.0-beta.5". 
Your url:
https://repo.maven.apache.org/maven2/org/powermock/powermock-module-junit4/powermock-2.0.0-beta.5/powermock-module-junit4-powermock-2.0.0-beta.5.pom
Correct url:
https://repo.maven.apache.org/maven2/org/powermock/powermock-module-junit4/2.0.0-beta.5/powermock-module-junit4-2.0.0-beta.5.pom

**Comment by freddyboucher** [comment]
Oops you're right!
Thanks
