### ISSUE TITLE
Support Junit 5

### ISSUE THREAD

**Issue by iamgollum** [powermock/powermock#906]
Background
--------------
The `powermock-module-junit4` beta release which claims to be compatible with 4+, the library will still not recognize:

`import org.junit.jupiter.api.Test;`

and it will throw a:

`org.powermock.api.mockito.ClassNotPreparedException`

when `@PrepareForTest` is applied on the class you want to static mock. If you want to use PowerMock, you will have to go back to Junit 4 or create a MockWrapper for your static method at this time. 

Request
---------

Support Junit 5 annotations in PowerMock 2.0

**Comment by thekingn0thing** [comment]
PowerMock support jUnit 4.x, not 4+. Unfortunately, I do not have time to implement supporting jUnit 5 in PowerMock 2.0. The release is already delayed for more than 7 months. 
There are more things to do than just support new annotation. PowerMock needs the ability to load test and all classes with its MockClassLoader. It could require a change in jUnit. You can read more here https://github.com/junit-team/junit5/issues/672

**Comment by thekingn0thing** [comment]
Duplicates #830

**Comment by isqo** [comment]
Hello,
The doc claims that you support JUnit 4.4 or above, which logically means junit 5. I spent hours understanding why it doesnt work until i found this issue, please be more specific and change it to 4.4-4.12, because it causes confusion. thanks in advance.

**Comment by DJViking** [comment]
This issue should not have been set Done, considering that #830 which this is a duplicate of did not make it into Powermock 2.0

**Comment by anhthuanit** [comment]
@thekingnothing 
I waiting for you a long time to introduce PowerMock supporting jUnit 5.
How is it going? Just give me a reason.

**Comment by simon-guldstrand-wcar** [comment]
Any updates on JUnit 5 support for PowerMock?

BR

**Comment by Joe-Tavarez** [comment]
If powermock doesn't support JUnit5, then what is this for? powermock-module-junit5
https://mvnrepository.com/artifact/org.powermock/powermock-module-junit5
