### ISSUE TITLE
Bad link in wiki.

### ISSUE THREAD

**Issue by wyattberlinic** [powermock/powermock#907]
I can't access this page in the wiki: https://github.com/powermock/powermock/wiki/MockSystem.md

It's linked from: https://github.com/powermock/powermock/wiki/Mockito
`Note: If you need to mock classes loaded by the java system/bootstrap classloader (those defined in the java.lang or java.net etc) you need to use this approach.`

**Comment by thekingn0thing** [comment]
thank you for reporting. I fixed the link
