### ISSUE TITLE
Mocking static classes with Powermock2 and Kotlin

### ISSUE THREAD

**Issue by RafaRuiz** [powermock/powermock#913]
Hello, in Android I've been using the version 1.6.1 of Powermock and all this implementation worked really good for statics.
It's not working now at all when I changed to 2.0.0-beta.5. Indeed, it didn't even work upgrading from my previous **1.6.1** to **1.7.1**.

I have this implementation:

    // Power Mockito
    testImplementation "org.powermock:powermock-api-mockito2:2.0.0-beta.5"
    testImplementation "org.powermock:powermock-module-junit4-rule-agent:2.0.0-beta.5"
    testImplementation "org.powermock:powermock-module-junit4:2.0.0-beta.5"
    //testImplementation 'org.powermock:powermock-module-junit4-rule:2.0.0-beta.5'

    // Mockito
    testImplementation "org.mockito:mockito-core:2.11.0"
    testImplementation "com.nhaarman:mockito-kotlin-kt1.1:1.5.0"
    androidTestImplementation("com.nhaarman:mockito-kotlin-kt1.1:1.5.0", {
        exclude group: 'org.mockito', module: 'mockito-core'
    })
    androidTestImplementation 'org.mockito:mockito-android:2.11.0'

and I'm trying to mock a static the same way I was doing with **1.6.1:**

    @RunWith(PowerMockRunner::class)
    @PrepareForTest(SharedPreferencesHelper.Companion::class, ConfigUseCaseTests::class)
    class ConfigUseCaseTests {
    
        lateinit var context: Context
    
        @Before
        fun setUp() {
            context = mock()
        }
    
        @Test
        fun getConfigs_fromJson() {
            PowerMockito.mockStatic(SharedPreferencesHelper.Companion::class.java)
    
            val instance = mock<SharedPreferencesHelper.Companion>()
            doReturn("foo")
                    .whenever(instance)
                    .loadString(isA(), anyString(), anyString(), anyString())
    //        whenever(instance.loadString(isA(), anyString(), anyString(), anyString())).thenReturn("foo") // This shows the same error
            PowerMockito.whenNew(SharedPreferencesHelper.Companion::class.java)
                    .withAnyArguments()
                    .thenReturn(instance)
    
            val mockedFoo = instance.loadString(context, "", "", "") // This shows "foo"
    
            val mockedCompanion = SharedPreferencesHelper.loadString(context, "", "", "") // This is throwing NullPointerException
    
            Assert.assertEquals(mockedCompanion, "foo")
        }
    }

My **SharedPreferencesHelper** looks like:

    class SharedPreferencesHelper {
        companion object {
    
            @Suppress("NON_FINAL_MEMBER_IN_OBJECT")
            open fun loadString(context: Context, fileName: String, key: String, defaultValue: String?): String? {
                val sharedPreferences = getWithFileName(context, fileName)
                return if (!sharedPreferences.contains(key)) {
                    defaultValue
                } else {
                    sharedPreferences.getString(key, defaultValue)
                }
            }
        }
    }

I've tried to play with the `open` but it didn't work.

**Exception:** (I don't understand it at all)

	java.lang.NullPointerException
		at my.package.ConfigUseCaseTests.getConfigs_fromJson(ConfigUseCaseTests.kt:45)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
		at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
		at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
		at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
		at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
		at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)

I can say, sometimes IT WORKS!! it happened when I changed the order of some static functions, it doesn't make sense !!!! 😭

I'm adding the video because it looks amazing that it happens just sometimes:
https://youtu.be/YZObVLcERBo

**Comment by RafaRuiz** [comment]
Some help wouldn't hurt at all

**Comment by charshep** [comment]
I get the same intermittent problem but I can't discern a pattern. I don't change any code.

**Comment by RafaRuiz** [comment]
I migrated to Mockk.io.
Changed my life.

**Comment by charshep** [comment]
Ugh, wish I'd know about Mockk.io before going down this rabbit hole. Thanks RafaRuiz.

**Comment by scotta1022** [comment]
Mockk is great, however it doesn't currently have PowerMockito's `whenNew` functionality, so right now we have a gap whether we use PowerMock or Mockk.

**Comment by RafaRuiz** [comment]
> Mockk is great, however it doesn't currently have PowerMockito's `whenNew` functionality, so right now we have a gap whether we use PowerMock or Mockk.

Maybe look at the constructor methods it has?
