### ISSUE TITLE
PowerMockito.replace does not replace calls from another classes

### ISSUE THREAD

**Issue by lasselindqvist** [powermock/powermock#916]
Version 1.7.1:

Trying to mock System.getProperty and System.setProperty with the following

PowerMockito.replace(PowerMockito.method(System.class, "setProperty", String.class, String.class)).with(
				PowerMockito.method(ProxySettingUtilsTest.class, "putToMap"));

PowerMockito.replace(PowerMockito.method(System.class, "getProperty", String.class)).with(
				PowerMockito.method(ProxySettingUtilsTest.class, "getFromMap"));

works when doing
System.setProperty("key1", "val1");
assertEquals("val1", System.getProperty("key1"));

but if I do
AnotherClass.setSystemProperty();
which only does
System.setProperty("key1", "val1");
the call is not mocked but a real call is made instead. Is this something that would be possible to mock or this a bug?

**Comment by thekingn0thing** [comment]
@lasselindqvist 
Have you added `AnotherClass` to `@PrepareForTest`? 

More information about mocking system classes [here](https://github.com/powermock/powermock/wiki/Mock-System)
