### ISSUE TITLE
PowerMockito 2 + Java 11 causes "An illegal reflective access operation has occurred"

### ISSUE THREAD

**Issue by antongorkovenko** [powermock/powermock#969]
Getting these for Java 11.0.2 + PowerMockito 2.0.0:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.powermock.reflect.internal.WhiteboxImpl (file:...) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of org.powermock.reflect.internal.WhiteboxImpl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

I tried to add this annotation, but it didn't help:
`@PowerMockIgnore({"com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "org.w3c.*"})`

**Comment by lfoppiano** [comment]
Any suggestion hint on this? 

The same occurs with PowerMock-EasyMock 2.0.2: 

```
    testCompile 'org.powermock:powermock-module-junit4:2.0.2'
    testCompile 'org.powermock:powermock-api-easymock:2.0.2'
```

and JDK 11: 

```
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)
```

**Comment by jacorelogic** [comment]
Having the same issue here. Not able to move to jdk 11.

**Comment by larabirabert** [comment]
+1 same issue

**Comment by cmdcarini** [comment]
Also seeing this issue

**Comment by javieraviles** [comment]
Also reproducible for Powermock 1.6.5 and jdk 11.0.5

**Comment by ssyadav** [comment]
+1 same issue

**Comment by victorrseloy** [comment]
+1 same issue

**Comment by fischmat** [comment]
+1 same here

**Comment by doubleo46** [comment]
Any update on this issue?

**Comment by scottazord** [comment]
+1

**Comment by Kongolan** [comment]
![image](https://user-images.githubusercontent.com/1629090/81488397-8ee75200-9268-11ea-9bc8-b04363a04332.png)
![image](https://user-images.githubusercontent.com/1629090/81488402-9eff3180-9268-11ea-97ea-ba3d322ccd1f.png)
https://stackoverflow.com/questions/56039341/get-declared-fields-of-java-lang-reflect-fields-in-jdk12/

For the devs, this is how you reflect into and set final variables with Java 11+. Hopefully they can add this to PowerMock, so it works there as well! I never tested it on Java 11, but it should work.

**Comment by johanhaleby** [comment]
Maybe someone could help out with a pull request?

**Comment by ghost** [comment]
+1 same here

**Comment by yuzzz** [comment]
+1

**Comment by lncarraro** [comment]
Same ocurring here. I'm also using Java 11

**Comment by Felk** [comment]
Please stop posting "+1"-style comments if you don't have any additional information on the issue, and use the issue's reaction feature instead (clicking the thumbs up).

**Comment by ThomasCraigNelson** [comment]
These warnings are due to the fact that as of Java 9 a module system was introduced.  Powermock relies heavily on reflection and other techniques to provide its functionality.  When these techniques cross module boundaries these warnings are thrown.  I found that by properly configuring the test runner to explicitly "open" the modules, I was able to eliminate these warnings with no change to powermock itself.  The configuration depends on the set of these crossed module boundaries.  In my case in a gradle environment the following eliminated these warnings:

test.jvmArgs = ["--illegal-access=debug",
                "--add-opens","java.logging/java.util.logging=ALL-UNNAMED",
                "--add-opens","java.base/java.time.zone=ALL-UNNAMED",
                "--add-opens","java.base/java.lang.reflect=ALL-UNNAMED",
                "--add-opens","java.base/java.security.cert=ALL-UNNAMED",
                "--add-opens","java.base/java.text=ALL-UNNAMED",
                "--add-opens","java.base/java.net=ALL-UNNAMED",
                "--add-opens","java.base/java.nio.charset=ALL-UNNAMED",
                "--add-opens","java.base/java.nio.file=ALL-UNNAMED",
                "--add-opens","java.base/sun.nio.fs=ALL-UNNAMED",
                "--add-opens","java.base/sun.security.x509=ALL-UNNAMED",
                "--add-opens","java.base/java.util.regex=ALL-UNNAMED",
                "--add-opens","java.base/java.util.stream=ALL-UNNAMED",
                "--add-opens","java.base/java.util.concurrent=ALL-UNNAMED",
                "--add-opens","java.base/java.util.concurrent.atomic=ALL-UNNAMED",
                "--add-opens","java.base/java.util.concurrent.locks=ALL-UNNAMED",
                "--add-opens","java.base/java.time=ALL-UNNAMED",
                "--add-opens","java.base/java.util=ALL-UNNAMED",
                "--add-opens","java.base/java.io=ALL-UNNAMED",
                "--add-opens","java.base/java.lang=ALL-UNNAMED"]

**Comment by roywasse** [comment]
configure your JDK compiler with this flag: --illegal-access=permit 
Now you will only get warnings

**Comment by tastybento** [comment]
For Maven users, put this in the POM:
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <argLine>
                        --illegal-access=permit
                    </argLine>
                </configuration>
            </plugin>
```
It's a workaround I would say, in that if you are in Java 16, it'll tell you that the illegal-access option is deprecated and will be removed at some point in the future.

**Comment by AlcipPopa** [comment]
I just upgraded our project from Java 8 to Java 11 and I solved this issue as a workaround with the following, in **Maven**  (check especially the **argLine** tags):

       <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.22.0</version>
                    <configuration>
                        <argLine>
                            --illegal-access=permit
                            --add-opens java.xml/jdk.xml.internal=ALL-UNNAMED
                        </argLine>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>2.22.0</version>
                    <configuration>
                        <argLine>
                            --illegal-access=permit
                        </argLine>
                    </configuration>
                </plugin>
            </plugins>
         </pluginManagement>

As you see the **argLine** has a new line for each new command. I only needed the  **java.xml/jdk.xml.internal** to be bypassed, because I had errors only on this Java 11 package; eventually you can add other packages aswell.

I didn't have to use any @PowermockIgnore annotation.

**Comment by nicoloboschi** [comment]
If it can help, with JDK 17 the `--illegal-access` option does not exist anymore. 
Currently, the only way to enable PowerMock with JDK 17+ is to add all the --add-opens to the jvm args when running tests.

**Comment by chittivenkat143** [comment]
In my case when am trying to access the private method **isBothAccountsAreActive** I got this

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.powermock.reflect.internal.WhiteboxImpl (file:...) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of org.powermock.reflect.internal.WhiteboxImpl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

So, I have done by doing this in Test Cases ( **Junit5 + JDK 11 + Powermockito**)
**Whitebox.invokeMethod(mock, "isBothAccountsAreActive", Optional.of(accountD), Optional.of(accountC))**

**Comment by hoangducnghi2207** [comment]
> For Maven users, put this in the POM:
> 
> ```
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-surefire-plugin</artifactId>
>                 <version>3.0.0-M5</version>
>                 <configuration>
>                     <argLine>
>                         --illegal-access=permit
>                     </argLine>
>                 </configuration>
>             </plugin>
> ```
> 
> It's a workaround I would say, in that if you are in Java 16, it'll tell you that the illegal-access option is deprecated and will be removed at some point in the future.

My project is using Gradle, how can I set up  "-illegal-access=permit" like you ?

**Comment by maidamemonimdex** [comment]
> > For Maven users, put this in the POM:
> > ```
> >             <plugin>
> >                 <groupId>org.apache.maven.plugins</groupId>
> >                 <artifactId>maven-surefire-plugin</artifactId>
> >                 <version>3.0.0-M5</version>
> >                 <configuration>
> >                     <argLine>
> >                         --illegal-access=permit
> >                     </argLine>
> >                 </configuration>
> >             </plugin>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It's a workaround I would say, in that if you are in Java 16, it'll tell you that the illegal-access option is deprecated and will be removed at some point in the future.
> 
> My project is using Gradle, how can I set up "-illegal-access=permit" like you ?

Did you find the solution?

**Comment by laughlast666** [comment]
> These warnings are due to the fact that as of Java 9 a module system was introduced. Powermock relies heavily on reflection and other techniques to provide its functionality. When these techniques cross module boundaries these warnings are thrown. I found that by properly configuring the test runner to explicitly "open" the modules, I was able to eliminate these warnings with no change to powermock itself. The configuration depends on the set of these crossed module boundaries. In my case in a gradle environment the following eliminated these warnings:
> 
> test.jvmArgs = ["--illegal-access=debug", "--add-opens","java.logging/java.util.logging=ALL-UNNAMED", "--add-opens","java.base/java.time.zone=ALL-UNNAMED", "--add-opens","java.base/java.lang.reflect=ALL-UNNAMED", "--add-opens","java.base/java.security.cert=ALL-UNNAMED", "--add-opens","java.base/java.text=ALL-UNNAMED", "--add-opens","java.base/java.net=ALL-UNNAMED", "--add-opens","java.base/java.nio.charset=ALL-UNNAMED", "--add-opens","java.base/java.nio.file=ALL-UNNAMED", "--add-opens","java.base/sun.nio.fs=ALL-UNNAMED", "--add-opens","java.base/sun.security.x509=ALL-UNNAMED", "--add-opens","java.base/java.util.regex=ALL-UNNAMED", "--add-opens","java.base/java.util.stream=ALL-UNNAMED", "--add-opens","java.base/java.util.concurrent=ALL-UNNAMED", "--add-opens","java.base/java.util.concurrent.atomic=ALL-UNNAMED", "--add-opens","java.base/java.util.concurrent.locks=ALL-UNNAMED", "--add-opens","java.base/java.time=ALL-UNNAMED", "--add-opens","java.base/java.util=ALL-UNNAMED", "--add-opens","java.base/java.io=ALL-UNNAMED", "--add-opens","java.base/java.lang=ALL-UNNAMED"]

thks.
It also works in my dev env of OSX+openjdk11+maven , no warning at all.
There is the ref:

                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <configuration>
                    <argLine>
                        --illegal-access=permit
                        --illegal-access=debug
                        --add-opens java.xml/jdk.xml.internal=ALL-UNNAMED
                        --add-opens java.logging/java.util.logging=ALL-UNNAMED
                        --add-opens java.base/java.time.zone=ALL-UNNAMED
                        --add-opens java.base/java.lang.reflect=ALL-UNNAMED
                        --add-opens java.base/java.security.cert=ALL-UNNAMED
                        --add-opens java.base/java.text=ALL-UNNAMED
                        --add-opens java.base/java.net=ALL-UNNAMED
                        --add-opens java.base/java.nio.charset=ALL-UNNAMED
                        --add-opens java.base/java.nio.file=ALL-UNNAMED
                        --add-opens java.base/sun.nio.fs=ALL-UNNAMED
                        --add-opens java.base/sun.security.x509=ALL-UNNAMED
                        --add-opens java.base/java.util.regex=ALL-UNNAMED
                        --add-opens java.base/java.util.stream=ALL-UNNAMED
                        --add-opens java.base/java.util.concurrent=ALL-UNNAMED
                        --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED
                        --add-opens java.base/java.util.concurrent.locks=ALL-UNNAMED
                        --add-opens java.base/java.time=ALL-UNNAMED
                        --add-opens java.base/java.util=ALL-UNNAMED
                        --add-opens java.base/java.io=ALL-UNNAMED
                        --add-opens java.base/java.lang=ALL-UNNAMED
                    </argLine>
