### ISSUE TITLE
Update wiki/downloads page with version 2.0 links

### ISSUE THREAD

**Issue by apwelsh** [powermock/powermock#972]
Thank you for this wonderful tool.  I would like to point out first that the readme.md download link does work, for those familiar with the maven system.  The wiki, however, has a link to the downloads, with descriptions of what each file is for.  These links have not been updated to point to the version 2.0.0 downloads.

https://github.com/powermock/powermock/wiki/Downloads

I am happy to update the wiki, but do not know if it is really appropriate, as I am just getting started for the first time with this project, and do not use maven.  As such, I am likely to make mistakes causing more confusion. 

Please update, or provide some basic guidance on the differences between 1.7 and 2.0 packages list so that we can update the download wiki page with up to date links.

**Comment by thekingn0thing** [comment]
Done
