### ISSUE TITLE
Using PowerMockRunner can't running all test cases at once

### ISSUE THREAD

**Issue by saintjab** [powermock/powermock#994]
I am using 
`
@RunWith(PowerMockRunner::class)
@PowerMockRunnerDelegate(JUnit4::class)
@PrepareForTest(ClassUnderTest::class)
` at my test class level wit multiple
 test cases under the class.  However, am not able to able to run all the test cases at once from the class level. Any time I try that, only first test case is run and the rest are ignored although I don't have any Ignore annotation.

I am using the following dependencies

//Testing dependencies
    def powermockVersion='1.7.4'
    def mockitoVersion='2.10.0'
    def powerVersion='2.0.2'

    testImplementation "org.powermock:powermock-api-mockito2:$powermockVersion"
    testImplementation "org.powermock:powermock-classloading-xstream:$powerVersion"
    testImplementation "org.powermock:powermock-module-junit4:$powerVersion"
    testImplementation "org.powermock:powermock-module-junit4-rule:$powerVersion"
    testImplementation "org.powermock:powermock-core:$powerVersion"
    testImplementation 'org.jetbrains.kotlin:kotlin-stdlib:1.3.40'
    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit:1.3.20'
    testImplementation 'org.mockito:mockito-inline:2.8.47'
    testImplementation "com.nhaarman.mockitokotlin2:mockito-kotlin:2.1.0"

Update: I also get **java.lang.NoClassDefFoundError: org/powermock/core/classloader/annotations/Mock** error, can it be related to the different versions of dependencies am using?

**Comment by rogeriogentil** [comment]
@saintjab: I didn't understand what dependency is 'powerVersion', but Mockito 2.10.0 and PowerMock 1.7.4 aren't widely compatible following this table → https://github.com/powermock/powermock/wiki/Mockito#supported-versions. However, I've also have been some problems with `java.lang.NoClassDefFoundError`.

**Comment by saintjab** [comment]
@rogeriogentil you are right. The problem was version compatibility. I finally found some versions of Mockito and PowerMock that were playing nice together

**Comment by rogeriogentil** [comment]
Great @saintjab! :slightly_smiling_face: Can you close this issue?
