### ISSUE TITLE
Powermock can't mock InetAddress.getLocalHost()

### ISSUE THREAD

**Issue by rabinXie** [powermock/powermock#995]
I want to mock InetAddress._getLocalHost_(), a static method, by using Powermock, but it seems that it doesn't work, codes as follows.
```
mockStatic(InetAddress.class);
doThrow(new UnknownHostException()).when(InetAddress.class);
InetAddress.getLocalHost();
```

It never throw exception.

**Comment by sam-ma** [comment]
I guess that's because you haven't actually called the method. The following works.

See [javadoc](https://static.javadoc.io/org.powermock/powermock-api-mockito2/2.0.2/org/powermock/api/mockito/expectation/PowerMockitoStubber.html#when-java.lang.Class-)

```java
mockStatic(InetAddress.class);
doThrow(new UnknownHostException()).when(InetAddress.class);
InetAddress.getLocalHost();

// this line triggers the method call
InetAddress.getLocalHost();
```

**Comment by rabinXie** [comment]
> ```java
> s line triggers the method call
> InetAddress.getLocalHost();
> ```
Thank you! It works.
